---
- name: deploy to Lightsail
  hosts: pis
  tasks:
    - name: Copy the compiled file to the Servers.
      ansible.builtin.copy:
        src: /mnt/c/Users/miten/Documents/MillionDollarProject/golang_v1/mlsch_de/bin/mlsch_de-linux-arm7
        dest: ~/mlsch_de
        # owner: ubuntu
        # group: ubuntu
        # 755 means read and execute access for everyone and also write access for the owner of the file. 
        mode: '0755'

    - name: Kill already running server.
      shell: |
        echo "LISTEN Ports when Starting"
        sudo lsof -i -P -n | grep LISTEN

        sudo pkill mlsch_de

        echo "LISTEN Ports after pkill"
        sudo lsof -i -P -n | grep LISTEN
        exit 0
      register: ps

    - name: Start the mlsch_de Server
      shell: "( ( nohup ~/mlsch_de -dev=true 1>/dev/null 2>&1 ) & )"
      async: 5
      poll: 0

    - name: Check for sucess.
      shell: |
        echo "Sleep 5 Seconds"
        sleep 5

        echo "LISTEN Ports after  Restart"
        sudo lsof -i -P -n | grep LISTEN

        echo "Tail of Logfile"
        tail ./Logs.log

        echo "-> Finished the Script."

        exit 0
      register: ps

    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://127.0.0.1:8080

    # - debug: var=ps

    